### ISSUE TITLE
IDEPIX_CLOUD flag not correctly set

### ISSUE THREAD

**Issue by marpet** [bcdev/snap-idepix#18]
It has been observed that the pixel_classif_flags.IDEPIX_CLOUD flag is set identically to the pixel_classif_flags.IDEPIX_CLOUD_SURE flag. Actually this flag should be the combination of pixel_classif_flags.IDEPIX_CLOUD_SURE and pixel_classif_flags.IDEPIX_CLOUD_AMBIGUOUS.

The mask IDEPIX_CLOUD corresponding to pixel_classif_flags.IDEPIX_CLOUD gives the correct result.
It is defined as: 
```
pixel_classif_flags.IDEPIX_CLOUD or pixel_classif_flags.IDEPIX_CLOUD_SURE or pixel_classif_flags.IDEPIX_CLOUD_AMBIGUOUS
```
After updating the flags this expression should only be like: `pixel_classif_flags.IDEPIX_CLOUD`

The image below shows the 3 flags with the mask as overlay.
![image](https://user-images.githubusercontent.com/204590/95744120-24ad6000-0c93-11eb-9d64-1097ddac2147.png)

This has been observed for the S2 Idepix results, probably this is common to all sensor implementations.

**Comment by clebreton** [comment]
I am commenting here because I am not sure how far we are on this task.
Whatever the definition of a flag, the corresponding mask in SNAP should reflect it one to one and not assume a combination of flags. Otherwise it needs to have a different name. This is what was confusing here.
There are two tasks here: 
1) to harmonise flag definition for S2 (and maybe for others? to check) with mask definition in SNAP, so that mask IDEPIX_CLOUD = pixel_classif_flags.IDEPIX_CLOUD
2) to change pixel_classif_flags.IDEPIX_CLOUD definition for S2 to pixel_classif_flags.IDEPIX_CLOUD = pixel_classif_flags.IDEPIX_CLOUD_SURE OR pixel_classif_flags.IDEPIX_CLOUD_AMBIGUOUS

**Comment by marpet** [comment]
Fixed by: https://github.com/bcdev/snap-idepix/commit/95e1412845645c683e7bf277b671584fb4b5fb42
